title: Hugo Huotari
logo: /assets/images/omakuva.png
theme: jekyll-theme-minimal
description: "Hello there! In this page, I showcase my PowerBI projects. <br/> <a href='https://www.linkedin.com/in/hugohuotari'>View my LinkedIn Profile</a>"
